# pod9.yaml
apiVersion: v1
kind: Pod
metadata:
 name: stress-cpu
spec:
 restartPolicy: Never
 containers:
  - name: stress
    image: polinux/stress
  #  args: ["stress", "--cpu", "1", "--timeout", "120s", "--verbose"]
    args: ["stress", "--vm", "1", "--vm-bytes", "300M", "--timeout", "120s", "--verbose"]
    resources:
      requests:
        cpu: "200m"
        memory: "64Mi"
      limits:
        cpu: "500m"
        memory: "128Mi"