apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app.kubernetes.io/name: MyApp # app.kubernetes.io/name: MyApp 값으로 설정된 label를 가진 Pod 선택.
  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
