apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-pod-{{ .Chart.Name}}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web


  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx-container
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
