apiVersion: v1
kind: Secret
metadata:
  name: secret-test

data:
  email: cmVydDg4MEBnbWFpbC5jb20=

stringData:
  username: root
  password: "1234"
  database: testdb
#stringData는 자동인코딩되고 data는 직접 인코딩해주어야한다`