# nginx-static-pod.yaml

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: web
spec:
  containers:
  - image: nginx
    name: nginx-container

    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: shared-volume

  volumes:
  - name: shared-volume
    persistentVolumeClaim:
      claimName: static-pvc