# liveness-httpGet.yaml

apiVersion: v1
kind: Pod
metadata:
  name: liveness-httpget-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:1.14.2
    ports:
     - containerPort: 80

    livenessProbe:
      httpGet:
        path: /wrong
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
      failureThreshold: 3  